config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users, :controllers => {:registrations => "user_registrations"}

  get 'home/index'

  root 'home#index'

  get 'about', to: 'home#about', as: :about
 # get 'contact', to: 'home#contact', as: :contact
  get 'contact', to: 'contactforms#new', as: 'contact'
  post 'contact', to: 'contactforms#create'
  get 'faq', to: 'home#faq'
  get 'tos', to: 'home#tos'
  get 'privacy', to: 'home#privacy'
  get 'sitemap', to: 'home#sitemap'
  get 'tournament/:id', to: 'tournaments#tournament'
  
  #contact other players
 # get 'contact_players', to: 'contact_players#new', as: 'contact_players'
  #post 'contact_players', to: 'contact_players#create'
  

  resources :users do
    resources :contact_players , only: [:new, :create]
    collection do
      get 'search'
    end
  end
  
  resources :tournaments do
    resources :teams
    resources :tournament_registrations do
      collection do
        post 'spectator'
      end
    end
    resources :sponsors
    resources :admins, only: [:index, :new, :create, :destroy]
    resources :check_in
    
    get 'checkout/registration', to: 'check_out#registration', as: 'registration_checkout'
    get 'checkout/spectator', to: 'check_out#spectator', as: 'spectator_checkout'
    get 'checkout/sponsor', to: 'check_out#sponsor', as: 'sponsor_checkout'
    member do
      delete 'quit', to: 'tournament_registrations#destroy', as: :quit
      get 'sponsor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
  belongs_to :tournament
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_player.rb
class ContactPlayer < ApplicationRecord
    
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :content


  validates :content,
    presence:{message:'Content cannot be empty'}

end

app/models/contactform.rb
class Contactform < ApplicationRecord
    
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence:  {message:'Name cannot be empty'}

  validates :email,
    presence:  {message:'Email cannot be empty'}


  validates :content,
    presence:  {message:'Content cannot be empty'}

    
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :team
  belongs_to :ticket_option
  has_many :scores

  scope :with_user_id, ->(user_id) { where(user_id: user_id) }

  def total_score
    scores.sum(:strokes)
  end
end

app/models/reg_sponsor.rb
class RegSponsor < ApplicationRecord
  belongs_to :tournament
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :player

  validates :hole, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :strokes, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  attr_accessor :logo 
  belongs_to :user
  belongs_to :tournament
  has_one :sponsor_option
  mount_uploader :logo , SponsorLogoUploader
end

app/models/sponsor_option.rb
class SponsorOption < ApplicationRecord
  belongs_to :tournament, optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  belongs_to :tournament

  def total_score
    players.joins(:scores).sum(:strokes)
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :ticket_option
end

app/models/ticket_option.rb
class TicketOption < ApplicationRecord
  belongs_to :tournament, optional: true
  has_many :tickets
end

app/models/tournament.rb
  class Tournament < ApplicationRecord
	# not sure what is the limit of a typical golf tournament,
	# this is just random
	validates :player_limit, :inclusion => 2..144
  validates :title, presence: true
  validates :title, uniqueness: { message: "%{value} already exists" }
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true
  validate :start_before_end

  mount_uploader :logo , TournamentLogoUploader

  has_many :teams
  has_many :sponsors
  has_many :admins
  has_many :players, through: :teams
  has_many :reg_sponsors
  has_many :sponsor_options
  has_many :ticket_options

  accepts_nested_attributes_for :sponsor_options, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :ticket_options, allow_destroy: true, reject_if: :all_blank

  # Validations
  def start_before_end
    return if start_datetime.blank? || end_datetime.blank?
    if start_datetime > end_datetime
      errors.add(:end_datetime, 'must be before start')
    end
  end

  def has_player? user_id
    players.exists? user_id: user_id
  end

  def has_sponsor? user_id
    sponsors.exists? user_id: user_id
  end

  def has_admin? user_id
    admins.exists? user_id: user_id
  end

  def player_availability
    (player_limit.to_f - players.size) / player_limit * 100
  end

  def has_sponsor? user_id
    sponsors.pluck(:user_id).include? user_id
  end

  def has_admin? user_id
    admins.pluck(:user_id).include? user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :addr, presence: true, length: {minimum:10, maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :players
  has_many :sponsors
  has_many :admins
  has_many :teams, through: :players
  has_many :tournaments # tournaments organized by the user
  mount_uploader :user_image , UserImageUploader
  
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true

  def name
    "#{fname} #{lname}"
  end

  def player_teams
    Team.joins(:plyers).where(players: { user_id: id }).distinct
  end

  def player_tournaments
    Tournament.joins(teams: :players).where(players: { user_id: id }).distinct
  end

  def admin_tournaments
    Tournament.joins(:admins).where(admins: { user_id: id }).distinct
  end

  def sponsor_tournaments
    Tournament.joins(:sponsors).where(sponsors: { user_id: id }).distinct
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@tournaments = Tournament.all
  end
  def about
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/contactforms_helper.rb
module ContactformsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_admins.html.haml
%table.table
  %tr
    %th= t('users.index.id')
    %th= t('users.index.first_name')
    %th= t('users.index.last_name')
    %th= t('users.index.email')
    %th= 'Actions'
  - admins.each do |admin|
    %tr
      %td= admin.user.id
      %td= admin.user.fname
      %td= admin.user.lname
      %td= admin.user.email
      %td= link_to 'Remove', tournament_admin_path(tournament, admin), method: :delete, data: { confirm: t('users.index.confirm')}

app/views/admins/index.html.haml
.container
  .row
    #blue
      %h3
        Administrators for Tournament: #{@tournament.title}
    = link_to 'Add Admin', new_tournament_admin_path, class: 'btn btn-theme'
    .admins
      = render partial: 'admins', locals: { tournament: @tournament, admins: @admins }

app/views/admins/new.html.haml
.container
  .row
    #blue
      %h3
        Admin Registration: #{@tournament.title}
    %h3 User Lookup
    = form_tag(tournament_admins_path(@tournament), method: 'POST') do
      .form-group
        = label_tag :email
        = text_field_tag :email, @email, class: 'form-control'
        %span#helpBlock.help-block Search for a user by email.
      .form-group
        = submit_tag 'Lookup User', class: 'btn btn-large btn-primary'

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">GOLFLY</a>
    </div>
    <div class="collapse navbar-collapse ">
      <ul class="nav navbar-nav navbar-left">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "HOME", root_path %></li>
        <li><a href="/tournaments"><%= t('header.tournaments') %></a></li>
        <li><a href="/about"><%= t('header.about') %></a></li>
        <li><a href="/contact"><%= t('header.contact') %></a></li>
        <li><a href="/faq"><%= t('header.faqs') %></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Profile', user_path(current_user) %>
              </li>
              <li>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>  
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Sign Up", new_registration_path(:user) %>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_message.html.haml
#flash
  - flash.each do |type, msg|
    .alert.fade.in{ class: bootstrap_class_for(type.to_sym) }
      %button.close{data: { dismiss: 'alert' }} x
      = msg

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golfly</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render '/layouts/header' %>
    <%= render '/layouts/message' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= stylesheet_link_tag 'http://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css' %>
    <script src="http://code.jquery.com/ui/1.12.0/jquery-ui.min.js"   integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="   crossorigin="anonymous"></script>
  </body>


  <footer>
    <div id="footerwrap">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <h4>About</h4>
          <div class="hline-w"></div>
          <p>Golfy is a web application that allow golf enthusiasts to organize and/or join local golf tournaments with ease!</p>
        </div>
        <div class="col-lg-4">
          <h4>Social Links</h4>
          <div class="hline-w"></div>
          <p>
            <a href="https://www.facebook.com/TheGolflyTournament"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/TheGolfly"><i class="fa fa-twitter"></i></a>
            <a href="https://www.instagram.com/TheGolfly/"><i class="fa fa-instagram"></i></a>
            <a href="https://www.linkedin.com/in/TheGolfly"><i class="fa fa-linkedin"></i></a>
          </p>
        </div>
        <div class="col-lg-4">
          <h4><%= t('application.links') %></h4>
          <div class="hline-w"></div>
          <p>
            <a href="tos.html"><%= t('application.tos') %></a>
            <br>
            <a href="privacy.html"><%= t('application.privacy_policy') %></a>
            <br>
            <a href="sitemap.html"><%= t('application.sitemap') %></a>
          </p>
        </div>
      
      </div><!--/row -->
    </div><!--/container -->
   </div><!--/footerwrap -->
  </footer>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8     col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">

					<%= pluralize(obj.errors.count, "error") %>

					prohibited this article from being saved:

				</h2>

				<div class="panel-body">

				<ul>

					<% obj.errors.full_messages.each do |msg| %>

					<li><%= msg %></li>

					<% end %>

				</ul>

				</div>

			</div>

		</div>

	</div>

</div>
<% end %>