config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users, :controllers => {:registrations => "user_registrations"}

  get 'home/index'

  root 'home#index'

  get 'about', to: 'home#about', as: :about
 # get 'contact', to: 'home#contact', as: :contact
  get 'contact', to: 'contactforms#new', as: 'contact'
  post 'contact', to: 'contactforms#create'
  get 'faq', to: 'home#faq'
  get 'tos', to: 'home#tos'
  get 'privacy', to: 'home#privacy'
  get 'sitemap', to: 'home#sitemap'
  get 'tournament/:id', to: 'tournaments#tournament'
  
  #contact other players
 # get 'contact_players', to: 'contact_players#new', as: 'contact_players'
  #post 'contact_players', to: 'contact_players#create'
  

  resources :users do
    resources :contact_players , only: [:new, :create]
    collection do
      get 'search'
    end
  end
  
  resources :tournaments do
    resources :teams
    resources :tournament_registrations do
      collection do
        post 'spectator'
      end
    end
    resources :sponsors
    resources :admins, only: [:index, :new, :create, :destroy]
    resources :check_in
    
    get 'checkout/registration', to: 'check_out#registration', as: 'registration_checkout'
    get 'checkout/spectator', to: 'check_out#spectator', as: 'spectator_checkout'
    get 'checkout/sponsor', to: 'check_out#sponsor', as: 'sponsor_checkout'
    member do
      delete 'quit', to: 'tournament_registrations#destroy', as: :quit
      get 'sponsor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :addr, presence: true, length: {minimum:10, maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :players
  has_many :sponsors
  has_many :admins
  has_many :teams, through: :players
  has_many :tournaments # tournaments organized by the user
  mount_uploader :user_image , UserImageUploader
  
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true

  def name
    "#{fname} #{lname}"
  end

  def player_teams
    Team.joins(:plyers).where(players: { user_id: id }).distinct
  end

  def player_tournaments
    Tournament.joins(teams: :players).where(players: { user_id: id }).distinct
  end

  def admin_tournaments
    Tournament.joins(:admins).where(admins: { user_id: id }).distinct
  end

  def sponsor_tournaments
    Tournament.joins(:sponsors).where(sponsors: { user_id: id }).distinct
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]

    @image_path = "http://www.eecg.toronto.edu/~stumm/stumm.jpg"

    # show tournaments
    @player_tournaments = @user.player_tournaments
    @admin_tournaments = @user.admin_tournaments
    @sponsor_tournaments = @user.sponsor_tournaments
  end

  def edit
    @user = User.find params[:id]
  end

  def create
    @user = User.create user_params
    redirect_to @user
  end

  def update
    @user = User.update params[:id], user_params

    redirect_to user_path
  end

  def destroy
    @user = User.find(params[:id]).destroy
 
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :phone, :user_image, :bio, :addr)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user, html: { multipart: true } do |f|
  .form-group.required
    = f.label :fname, t('users.form.first_name')
    = f.text_field :fname, class: 'form-control'
  .form-group.required
    = f.label :lname, t('users.form.last_name')
    = f.text_field :lname, class: 'form-control'
  .form-group.required
    = f.label :email, t('users.form.email')
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :phone, t('users.form.phone')
    = f.telephone_field :phone, class: 'form-control'
  .form-group
    = f.label :addr, t('users.form.addr')
    = f.text_area :addr, class: 'form-control'
  .form-group
    = f.label :bio, t('users.form.bio')
    = f.text_area :bio, class: 'form-control'
  .form-group
    = f.label :user_image, t('users.form.user_image')
    = f.file_field :user_image, class: 'form-control-file'
  .form-group
    = f.submit 'Submit', class: 'btn btn-primary btn-large'

app/views/users/_tournament_element.html.haml
.col-md-3
  -#= image_tag 'http://winklerchamber.com/wp-content/uploads/2016/04/golf-ball-by-hole.jpg'
  = image_tag  tournament.logo_url.to_s, height: '200', width: '200'
.col-md-3
  = link_to tournament.title, tournament_path(id: tournament.id)
.col-md-2
  = tournament.location || t('users.t_element.unknown_location')
.col-md-2
  = tournament.start_datetime.to_formatted_s(:long_ordinal)
.col-md-2
  = tournament.end_datetime.to_formatted_s(:long_ordinal)

app/views/users/edit.html.erb
<% if current_user.id == @user.id %>
  <div class="container">
    <div class="row">
      <h1><%= t('users.edit.title') %></h1>
      <%= render 'form' %>
    </div>
  </div>
<% else %>
  <div class="alert alert-warning">
    <strong>Warning!</strong> <%= t('users.edit.warning_message') %>
  </div>
  <div class="container">
    <div class="row">
      <%= link_to t('users.edit.return_message'), user_path(@user.id), class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h1>Users</h1>
    <%= link_to t('users.index.signup_btn'), new_user_path, {:class=>"btn btn-theme"} %>
    <table class="table table-bordered">
      <tr>
        <th><%= t('users.index.id') %></th>
        <th><%= t('users.index.first_name') %></th>
        <th><%= t('users.index.last_name') %></th>
        <th><%= t('users.index.email') %></th>
        <th colspan="6"><%= t('users.index.action') %></th>
      </tr>
     
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.fname %></td>
          <td><%= user.lname %></td>
          <td><%= user.email %></td>
          <td><%= link_to t('users.index.show'), user_path(user) %></td>
          <td><%= link_to t('users.index.edit'), edit_user_path(user) %></td>
          <td><%= link_to t('users.index.destroy'), user_path(user),
                  method: :delete,
                  data: { confirm: t('users.index.confirm') } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1><%= t('users.new.title') %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h1> User Data </h1>
    <p> 
      <strong>First Name:</strong>
      <%= @user.fname %>
    </p>

    <p> 
      <strong>Last Name:</strong>
      <%= @user.lname %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Phone number:</strong>
      <%= @user.phone %>
    </p>

    <p>     
      <strong>Address:</strong>
      <%= @user.addr %>
    </p>
    <%= link_to 'Edit user', edit_user_path, {:class=>"btn btn-theme"} %>
  </div>
</div>

app/views/users/show.html.haml
.container
  .col-md-3.profile-info
    -#= image_tag @image_path
    =image_tag @user.user_image_url.to_s, height: '200', width: '200'
    .profile-name= @user.name
    %div= @user.email
    %div= @user.addr
    %div= @user.bio
    - if current_user.id == @user.id
      = button_to t('users.show.edit_profile'), { action: 'edit', id: @user.id}, method: :get, class: 'btn btn-default edit-profile'
    - else
      = button_to ('Email this user'), new_user_contact_player_path(@user.id), method: :get, class: 'btn btn-default edit-profile' 
      
  .col-md-9
    .row
      %h3 
        = t('users.show.your_tournaments')
    .row
      %h4 Tournaments You Have Played In
      .player-tournaments.col-md-12
        - if @player_tournaments.empty?
          = t('users.show.sorry_no_tournaments')
        .col-md-12
          - @player_tournaments.each do |t|
            .row.tournament-element
              = render partial: 'tournament_element', locals: {tournament: t }
    .row
      %h4 Tournaments You Have Sponsored
      .sponsor-tournaments.col-md-12
        - if @sponsor_tournaments.empty?
          = t('users.show.sorry_not_sponsor')
        .col-md-12
          - @sponsor_tournaments.each do |t|
            .row.tournament-element
              = render partial: 'tournament_element', locals: {tournament: t }
    .row
      %h4 Tournaments You Are An Admin For
      .admin-tournaments.col-md-12
        - if @sponsor_tournaments.empty?
          = t('users.show.sorry_not_admin')
        .col-md-12
          - @admin_tournaments.each do |t|
            .row.tournament-element
              = render partial: 'tournament_element', locals: {tournament: t }