config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users, :controllers => {:registrations => "user_registrations"}

  get 'home/index'

  root 'home#index'

  get 'about', to: 'home#about', as: :about
 # get 'contact', to: 'home#contact', as: :contact
  get 'contact', to: 'contactforms#new', as: 'contact'
  post 'contact', to: 'contactforms#create'
  get 'faq', to: 'home#faq'
  get 'tos', to: 'home#tos'
  get 'privacy', to: 'home#privacy'
  get 'sitemap', to: 'home#sitemap'
  get 'tournament/:id', to: 'tournaments#tournament'
  
  #contact other players
 # get 'contact_players', to: 'contact_players#new', as: 'contact_players'
  #post 'contact_players', to: 'contact_players#create'
  

  resources :users do
    resources :contact_players , only: [:new, :create]
    collection do
      get 'search'
    end
  end
  
  resources :tournaments do
    resources :teams
    resources :tournament_registrations do
      collection do
        post 'spectator'
      end
    end
    resources :sponsors
    resources :admins, only: [:index, :new, :create, :destroy]
    resources :check_in
    
    get 'checkout/registration', to: 'check_out#registration', as: 'registration_checkout'
    get 'checkout/spectator', to: 'check_out#spectator', as: 'spectator_checkout'
    get 'checkout/sponsor', to: 'check_out#sponsor', as: 'sponsor_checkout'
    member do
      delete 'quit', to: 'tournament_registrations#destroy', as: :quit
      get 'sponsor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tournament.rb
  class Tournament < ApplicationRecord
	# not sure what is the limit of a typical golf tournament,
	# this is just random
	validates :player_limit, :inclusion => 2..144
  validates :title, presence: true
  validates :title, uniqueness: { message: "%{value} already exists" }
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true
  validate :start_before_end

  mount_uploader :logo , TournamentLogoUploader

  has_many :teams
  has_many :sponsors
  has_many :admins
  has_many :players, through: :teams
  has_many :reg_sponsors
  has_many :sponsor_options
  has_many :ticket_options

  accepts_nested_attributes_for :sponsor_options, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :ticket_options, allow_destroy: true, reject_if: :all_blank

  # Validations
  def start_before_end
    return if start_datetime.blank? || end_datetime.blank?
    if start_datetime > end_datetime
      errors.add(:end_datetime, 'must be before start')
    end
  end

  def has_player? user_id
    players.exists? user_id: user_id
  end

  def has_sponsor? user_id
    sponsors.exists? user_id: user_id
  end

  def has_admin? user_id
    admins.exists? user_id: user_id
  end

  def player_availability
    (player_limit.to_f - players.size) / player_limit * 100
  end

  def has_sponsor? user_id
    sponsors.pluck(:user_id).include? user_id
  end

  def has_admin? user_id
    admins.pluck(:user_id).include? user_id
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :sponsor]
  before_action :is_tournament_admin!, only: [:edit, :update, :destroy]

  def index
    @tournaments = Tournament.all
  end

  def new
    @tournament = Tournament.new
  end

  def show
    @tournament = Tournament.find params[:id]
    @players = @tournament.players
    @users = @players.map &:user
    @sponsors = @tournament.sponsors
    @ticket_options = @tournament.ticket_options
    @sponsor_options = @tournament.sponsor_options
    @available_spot = @tournament.player_availability.to_i
    
    # show google map using tournament address
    gmap_root_url = "https://www.google.com/maps/embed/v1/place"
    gmapkey = "AIzaSyC-3qdPg9MxPjVXNNyzuDzJU7IpNLcOb1U"
    gmap_addr = @tournament.location.squish.tr(" ",",")
    @tournament_gmap_url = gmap_root_url + "?key=" + gmapkey + "&q=" + gmap_addr
  end

  def edit
    @tournament = Tournament.find params[:id]
    @ticket_options = @tournament.ticket_options
    @sponsor_options = @tournament.sponsor_options
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if @tournament.save
      @tournament.admins.create user_id: current_user.id
      flash[:success] = 'Tournament has been successfully created'
      redirect_to tournament_path(@tournament)
    else
      render 'new'
    end
  end

  def update
    @tournament = Tournament.find(params[:id])  
    if @tournament.update_attributes tournament_params
      redirect_to @tournament, notice: 'Tournament was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @tournament = Tournament.find params[:id]
    @tournament.destroy
    redirect_to tournaments_path
  end

  # current user sponsors the tournament
  def sponsor
    user = current_user
    tournament = Tournament.find params[:id]
    #tournament.sponsors.create(user: user) if user && !tournament.has_sponsor?(user.id)
    redirect_to tournament_path(tournament)
  end

  private

  def tournament_params
    params.require(:tournament).permit(:title, :location, :is_private, :golf_format, :schedule, :email, :phone, :features,
                                       :location, :start_datetime, :end_datetime, :description, :player_limit, :user_id,:logo,
                                       ticket_options_attributes: [:id, :ttype, :price, :_destroy],
                                       sponsor_options_attributes: [:id, :ttype, :price, :_destroy] )
  end

  def is_tournament_admin!
    tournament = Tournament.find params['id'].to_i
    unless tournament.has_admin? current_user.id
      flash[:error] = 'Only tournament admins can edit or destroy a tournament.'
      redirect_to tournament
    end
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.haml
= form_for @tournament, html: { multipart: true } do |f|
  .form-group.required
    = f.label :title, t('tournaments.form.name')
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :is_private, t('tournaments.form.is_private')
    = f.check_box :is_private, class: 'form-check'
  .form-group.required
    = f.label :player_limit, t('tournaments.form.player_limit')
    = f.number_field :player_limit, in: 2..144, class: 'form-control'
  .form-group.required
    = f.label :start_datetime, t('tournaments.form.start_datetime')
    = f.date_field :start_datetime, placeholder: 'YYYY-MM-DD HH:MM', class: 'form-control'
  .form-group.required
    = f.label :end_datetime, t('tournaments.form.end_datetime')
    = f.date_field :end_datetime, placeholder: 'YYYY-MM-DD HH:MM', class: 'form-control'
  .form-group.required
    = f.label :location, t('tournaments.location')
    = f.text_area :location, placeholder: 'Address', class: 'form-control'
  .form-group
    = f.label :description, t('tournaments.form.desc')
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :golf_format, t('tournaments.form.format')
    = f.text_field :golf_format, class: 'form-control'
  .form-group
    = f.label :tournament_schedule, t('tournaments.form.schedule')
    = f.text_area :schedule, class: 'form-control'
  .form-group
    = f.label :features, t('tournaments.form.features')
    = f.text_area :features, class: 'form-control'
  .form-group
    = f.label :email, t('tournaments.form.email')
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :phone, t('tournaments.form.phone')
    = f.text_field :phone, class: 'form-control'
  .form-group
    = f.label :logo, t('tournaments.form.logo')
    = f.file_field :logo, class: 'form-control-file'  
  %h4= t('tournaments.form.ticket_options')
  .form-group
    = f.fields_for :ticket_options do |ff|
      = render 'ticket_option_fields', f: ff
    = link_to_add_association t('tournaments.form.add_ticket'), f, :ticket_options
  %h4= t('tournaments.form.sponsor_options')
  .form-group
    = f.fields_for :sponsor_options do |ff|
      = render 'sponsor_option_fields', f: ff
    = link_to_add_association t('tournaments.form.add_sponsor'), f, :sponsor_options
  .form-group
    = f.submit 'Submit Tournament', class: 'btn btn-primary btn-large'

app/views/tournaments/_sponsor_option_fields.html.haml
.nested-fields.form-inline.form-group
  = f.label :ttype, t('tournaments.form.sponsor_type')
  = f.text_field :ttype, class: 'form-control'
  = f.label :price, t('tournaments.form.price')
  = f.number_field :price, min: 0, class: 'form-control'

  = link_to_remove_association t('tournaments.form.remove'), f

app/views/tournaments/_ticket_option_fields.html.haml
.nested-fields.form-inline.form-group
  = f.label :ttype, t('tournaments.form.sponsor_type')
  = f.text_field :ttype, class: 'form-control'
  = f.label :price, t('tournaments.form.price')
  = f.number_field :price, min: 0, class: 'form-control'

  = link_to_remove_association t('tournaments.form.remove'), f

app/views/tournaments/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit Tournament</h1>
    <%= render 'shared/errors', obj: @tournament if @tournament.errors.present? %>
    <%= render partial: 'form' %>
	  <%= link_to 'Back', tournaments_path %>
  </div>
</div>

<script type="text/javascript">
function removeRow(item) {
  $(item).parents('tr').remove();
}

function addRow(templateRow, tableBody) {
  var row = templateRow.clone();
  $(":input", row).attr("disabled", false);
  row.removeAttr('id');
  tableBody.append(row);
  row.show();
}
</script>

app/views/tournaments/index.html.erb
<div id="portfoliowrap">
    <div class="container">
      <div class="row">
        <h1>Tournaments</h1>
        <h3><%= t('tournaments.index.title') %></h3>
      </div>
      <div class="row">
        <%= link_to t('tournaments.index.tournament.create'), new_tournament_path, {:class=>"btn btn-theme"} %>
      </div> 
    </div>
</div><!-- /headerwrap -->

<div class="container">
  <div class="row">
    <table id="tournamentsall" class="table table-striped">
      <thead>
        <tr>
          <th><%= t('tournaments.index.table.title') %></th>
          <th><%= t('tournaments.index.table.location') %></th>
          <th><%= t('tournaments.index.table.start_date') %></th>
          <th><%= t('tournaments.index.table.until') %></th>
          <th><%= t('tournaments.index.table.desc') %></th>
        </tr>
      </thead>
      <tbody>
        <% @tournaments.each do |tournament| %>
          <tr>
            <td><%= link_to tournament.title, tournament_path(tournament) %></td>
            <td><%= tournament.location %></td>
            <td><%= tournament.start_datetime.strftime('%v') %></td>
            <td><%= tournament.end_datetime.strftime('%v') %></td>
            <td><%= t('tournaments.index.tournament.desc', desc: tournament.description) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tournaments/new.html.erb
<div class="container">
  <div class="row">
    <h1> Create a new tournament!</h1>
    <%= render 'shared/errors', obj: @tournament if @tournament.errors.present? %>
    <%= render '/tournaments/form' %>
  </div>
</div>

app/views/tournaments/show.html.erb
<div class = "container">
    
    <!-- <div class="jumbotron"> -->
    <div class="jumbotron">
      <!-- Tournament Logo, Name and Description -->
      <div class="row">

        <!-- Logo -->
        <div class = "col-md-4">
          <div class="center-block" align="center">
            <%= image_tag @tournament.logo_url.to_s,  class: "img-responsive", width: "250" %>
          </div>
        </div>

        <!-- Name and Description -->
        <div class = "col-md-8">
              <h1><%= @tournament.title%></h1>
              <p><%= @tournament.description%></p>
        </div>
        <!-- Edit button, only available for tournament admins -->
        <div class="col-md-8 row">
          <% if signed_in? && @tournament.has_admin?(current_user.id) %>
            <div class="col-md-6">
              <%= link_to 'Edit', edit_tournament_path(@tournament), class: 'btn btn-default btn-lg btn-block' %>
            </div>
            <div class="col-md-6">
              <%= link_to 'Manage Tournament Admins', tournament_admins_path(tournament_id: @tournament.id), class: 'btn btn-default btn-lg btn-block' %>
            </div>
          <% end %>
        </div>
      </div>
      <hr>

      <!-- Location -->
      <h3>Location and Time</h3>
      <div class = "row">
        <div class = "col-md-12">
          <p><strong><%= t('tournaments.show.place') %></strong> <%= @tournament.location%></p>
        </div>
        <div class = "col-md-12">
          <iframe
            width="100%"
            height="300"
            frameborder="0" style="border:0"
            src= "<%= @tournament_gmap_url %>" allowfullscreen>
          </iframe>
        </div>
      </div>

      <!-- Timing -->
      <div class="row">
        <div class = "col-md-4">
          <p><strong>Start Date:</strong> <%= @tournament.start_datetime.strftime('%v') %></p>
        </div>
        <div class = "col-md-4">
          <p><strong>End Date:</strong> <%= @tournament.end_datetime.strftime('%v') %></p>
        </div>
      </div>
      <hr>

      <!-- Contact Information -->
      <h3>Contact Information</h3>
      <div class="row">
        <div class = "col-md-4">
          <p><strong><%= t('tournaments.show.phone') %></strong> <%= number_to_phone(@tournament.phone)%></p>
        </div>
        <div class = "col-md-8">
          <p><strong><%= t('tournaments.show.email') %></strong> <%= @tournament.email %></p>
        </div>
      </div>
      <hr>
      <!-- Buttons -->
      <div class="row">
        <!-- Join Tournament -->
        <div class="col-md-4">
          <% if signed_in? && @tournament.has_player?(current_user.id) %>
            <%= link_to t('tournaments.button.quit'), quit_tournament_path(@tournament), method: :delete, class: 'btn btn-default btn-lg btn-block' %>
          <% else %>
            <%= link_to t('tournaments.button.join'), new_tournament_tournament_registration_path(@tournament), class: 'btn btn-primary btn-lg btn-block' %>
          <% end %>
        </div>

        <!-- Sponsor Tournament -->
        <div class="col-md-4">
          <% if signed_in? && @tournament.has_sponsor?(current_user.id) %>
            <%= link_to t('tournaments.button.sponsor'), new_tournament_sponsor_path(@tournament), {:class=>"btn btn-primary btn-lg btn-block"} %>
          <% else %>
            <%= link_to t('tournaments.button.sponsor'), new_tournament_sponsor_path(@tournament), {class: "btn btn-primary btn-lg btn-block"} %>
          <% end %>
        </div>

        <!-- Checkin Tournament -->
        <div class="col-md-4">
          <%= link_to t('tournaments.button.check_in'), new_tournament_check_in_path(@tournament), {class: "btn btn-primary btn-lg btn-block"} %>
        </div> 
      </div>
    </div>
</div>

<!-- Addition information -->

<div class ="container">

  <div class = "row">
    <div class = "col-md-12">
      <h2>Available Spots:</h2>
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="<%= @available_spot %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @available_spot %>%;">
          <!-- <div class="progress-bar" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"> -->
          <%= @available_spot %>% remaining
        </div>
      </div>
    </div>
  </div>

  <!-- display ticket sales for administrator -->
  <% if signed_in? && @tournament.has_admin?(current_user.id) %>
  <div class="row">
    <hr>
    <h3>Admin Console</h3>
    <div id="chart" />
      <script>
      var chart = c3.generate({
        title: {
          text: 'Revenue by Ticket Type'
        },
        bindto: '#chart',
        data: {
          x: 'x',
          columns: [
            <%=raw (['x'].concat @ticket_options.map{|x| x.ttype}).to_json %>,
            <%=raw (['Revenue ($)'].concat @ticket_options.map{|o| @players.map{|p| p.ticket_option}.count(o) * o.price}).to_json %>
          ],
          type: 'bar',
        },
        axis: {
            x: {
                type: 'categorized' // this is needed to load string x value
            }
        }
      });
      </script>
    <% end %>
  </div>


  <!-- Display all other information such as golf_format, schedule, features -->
  <div class = "row">
    <hr>
    <div class = "col-md-6">
      <h4>Golf Format</h4>
      <p><%= @tournament.golf_format%></p>
    </div>
    <div class = "col-md-6">
      <h4>Tournament Features</h4>
      <p><%= @tournament.features%></p>
    </div>
    <div class = "col-md-12">
      <h4>Tournament Schedule</h4>
      <p><%= @tournament.schedule%></p>
    </div>
  </div>

  <!-- display all ticket types available for purchase -->
  <div class="row">
    <hr>
    <div class = "col-md-6">
      <h4><%= t('tournaments.show.ticket_options') %></h4>
      <table class="table table-bordered table-striped">
        <tr>
          <th>Type</th>
          <th><%= t('tournaments.show.table.price') %></th>
        </tr>
        <% @ticket_options.each do |to| %>
            <tr>
              <td><%= to.ttype %></td>
              <td><%= to.price %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>

  <!-- display all SPONSOR OPTIONS in a table -->
  <div class = "row">
    <div class = "col-md-6">
      <h4><%= t('tournaments.show.sponsor_options') %></h4>
      <table class="table table-bordered table-striped">
        <tr>
          <th>Type</th>
          <th><%= t('tournaments.show.table.price') %></th>
        </tr>
        <% @sponsor_options.each do |so| %>
            <tr>
              <td><%= so.ttype %></td>
              <td><%= so.price %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>

  <!-- display all sponsors in a table -->
  <div class="row">
    <hr>
    <div class="col-md-12">
      <h3><%= t('tournaments.show.our_proud_sponsors') %></h3>
      <table class="table table-striped">
        <tr>
          <th><%= t('tournaments.show.table.logo') %></th>
          <th><%= t('tournaments.show.table.type') %></th>
          <th><%= t('tournaments.show.table.first_name') %></th>
          <th><%= t('tournaments.show.table.last_name') %></th>
          <th><%= t('tournaments.show.table.email') %></th>
          <th><%= t('tournaments.show.table.website') %></th>
        </tr>
        <% @sponsors.each do |s| %>
          <tr>
            <td></td>
            <td>
              <% if s.sponsor_opt_id.present? %>
                  <%=  @sponsor_options.find(s.sponsor_opt_id).ttype %>
              <% end %>
            </td>
            <td><%= s.user.fname %></td>
            <td><%= s.user.lname %></td>
            <td><%= s.email || '-' %></td>
            <td><%= s.website || '-' %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <!-- display all participants in a table -->
  <div class="row">
    <hr>
    <div class="col-md-12">
      <h3><%= t('tournaments.table.participant_list') %></h3>
      <table class="table table-striped">
        <tr>
          <th><%= t('tournaments.table.first_name') %></th>
          <th><%= t('tournaments.table.last_name') %></th>
          <th><%= t('tournaments.table.joined') %></th>
          <th><%= t('tournaments.table.team') %></th>
          <% if signed_in? && @tournament.has_admin?(current_user.id) %>
            <th><%= t('tournament.table.phone') %></th>
          <% end %>
          <th><%= t('tournaments.table.view_profile') %></th>
        </tr>
        <% @players.each do |player| %>
          <tr>
            <td><%= player.user.fname %></td>
            <td><%= player.user.lname %></td>
            <td><%= player.created_at %></td>
            <td><%= player.team.name %></td>
            <% if signed_in? && @tournament.has_admin?(current_user.id) %>
              <td><%= player.user.phone %></td>
            <% end %>
            <td><%= link_to user_path(player.user), class: "btn btn-default" do %>
                  <i class="fa fa-user-circle">
                    <%= t('tournaments.table.user_profile') %>
                  </i>
                <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  
</div>