config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users, :controllers => {:registrations => "user_registrations"}

  get 'home/index'

  root 'home#index'

  get 'about', to: 'home#about', as: :about
 # get 'contact', to: 'home#contact', as: :contact
  get 'contact', to: 'contactforms#new', as: 'contact'
  post 'contact', to: 'contactforms#create'
  get 'faq', to: 'home#faq'
  get 'tos', to: 'home#tos'
  get 'privacy', to: 'home#privacy'
  get 'sitemap', to: 'home#sitemap'
  get 'tournament/:id', to: 'tournaments#tournament'
  
  #contact other players
 # get 'contact_players', to: 'contact_players#new', as: 'contact_players'
  #post 'contact_players', to: 'contact_players#create'
  

  resources :users do
    resources :contact_players , only: [:new, :create]
    collection do
      get 'search'
    end
  end
  
  resources :tournaments do
    resources :teams
    resources :tournament_registrations do
      collection do
        post 'spectator'
      end
    end
    resources :sponsors
    resources :admins, only: [:index, :new, :create, :destroy]
    resources :check_in
    
    get 'checkout/registration', to: 'check_out#registration', as: 'registration_checkout'
    get 'checkout/spectator', to: 'check_out#spectator', as: 'spectator_checkout'
    get 'checkout/sponsor', to: 'check_out#sponsor', as: 'sponsor_checkout'
    member do
      delete 'quit', to: 'tournament_registrations#destroy', as: :quit
      get 'sponsor'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
  belongs_to :tournament
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_player.rb
class ContactPlayer < ApplicationRecord
    
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :content


  validates :content,
    presence:{message:'Content cannot be empty'}

end

app/models/contactform.rb
class Contactform < ApplicationRecord
    
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence:  {message:'Name cannot be empty'}

  validates :email,
    presence:  {message:'Email cannot be empty'}


  validates :content,
    presence:  {message:'Content cannot be empty'}

    
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :team
  belongs_to :ticket_option
  has_many :scores

  scope :with_user_id, ->(user_id) { where(user_id: user_id) }

  def total_score
    scores.sum(:strokes)
  end
end

app/models/reg_sponsor.rb
class RegSponsor < ApplicationRecord
  belongs_to :tournament
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :player

  validates :hole, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :strokes, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  attr_accessor :logo 
  belongs_to :user
  belongs_to :tournament
  has_one :sponsor_option
  mount_uploader :logo , SponsorLogoUploader
end

app/models/sponsor_option.rb
class SponsorOption < ApplicationRecord
  belongs_to :tournament, optional: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  belongs_to :tournament

  def total_score
    players.joins(:scores).sum(:strokes)
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :ticket_option
end

app/models/ticket_option.rb
class TicketOption < ApplicationRecord
  belongs_to :tournament, optional: true
  has_many :tickets
end

app/models/tournament.rb
  class Tournament < ApplicationRecord
	# not sure what is the limit of a typical golf tournament,
	# this is just random
	validates :player_limit, :inclusion => 2..144
  validates :title, presence: true
  validates :title, uniqueness: { message: "%{value} already exists" }
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true
  validate :start_before_end

  mount_uploader :logo , TournamentLogoUploader

  has_many :teams
  has_many :sponsors
  has_many :admins
  has_many :players, through: :teams
  has_many :reg_sponsors
  has_many :sponsor_options
  has_many :ticket_options

  accepts_nested_attributes_for :sponsor_options, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :ticket_options, allow_destroy: true, reject_if: :all_blank

  # Validations
  def start_before_end
    return if start_datetime.blank? || end_datetime.blank?
    if start_datetime > end_datetime
      errors.add(:end_datetime, 'must be before start')
    end
  end

  def has_player? user_id
    players.exists? user_id: user_id
  end

  def has_sponsor? user_id
    sponsors.exists? user_id: user_id
  end

  def has_admin? user_id
    admins.exists? user_id: user_id
  end

  def player_availability
    (player_limit.to_f - players.size) / player_limit * 100
  end

  def has_sponsor? user_id
    sponsors.pluck(:user_id).include? user_id
  end

  def has_admin? user_id
    admins.pluck(:user_id).include? user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :addr, presence: true, length: {minimum:10, maximum: 50}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :players
  has_many :sponsors
  has_many :admins
  has_many :teams, through: :players
  has_many :tournaments # tournaments organized by the user
  mount_uploader :user_image , UserImageUploader
  
  validates :fname, presence: true
  validates :lname, presence: true
  validates :email, presence: true

  def name
    "#{fname} #{lname}"
  end

  def player_teams
    Team.joins(:plyers).where(players: { user_id: id }).distinct
  end

  def player_tournaments
    Tournament.joins(teams: :players).where(players: { user_id: id }).distinct
  end

  def admin_tournaments
    Tournament.joins(:admins).where(admins: { user_id: id }).distinct
  end

  def sponsor_tournaments
    Tournament.joins(:sponsors).where(sponsors: { user_id: id }).distinct
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@tournaments = Tournament.all
  end
  def about
  end

  def about
  end

  def contact
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
  def new
  	@team = Team.new
  end

  def create
  	@team = Team.new(team_params)
  	if @team.save
      redirect_to new_tournament_tournament_registration_path
    else
      redirect_to new_tournament_team_path
  	end
  end

  private

  def team_params
  	params.require(:team).permit(:tournament_id, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]

    @image_path = "http://www.eecg.toronto.edu/~stumm/stumm.jpg"

    # show tournaments
    @player_tournaments = @user.player_tournaments
    @admin_tournaments = @user.admin_tournaments
    @sponsor_tournaments = @user.sponsor_tournaments
  end

  def edit
    @user = User.find params[:id]
  end

  def create
    @user = User.create user_params
    redirect_to @user
  end

  def update
    @user = User.update params[:id], user_params

    redirect_to user_path
  end

  def destroy
    @user = User.find(params[:id]).destroy
 
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :phone, :user_image, :bio, :addr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/contactforms_helper.rb
module ContactformsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div id = "blue">
	<div class="container">
		<div class = "row">
			<h3>About Us</h3>
		</div>
	</div>
</div>

<div class = "container centered">
	<h3>What is Golfly?</h3>
	<p>
		Golfy is a web application that allow golf enthusiasts to organize and/or join local golf tournaments with ease!
	</p>
	<hr>
	<h3>What does Golfly do?</h3>
	<p>
		If you are an organizer:<br><br>

		You can set up tournaments!<br>
		You can manage your tournaments!<br>
		You can set up online payment system! <br>
		You can access real-time imformation about the tournaments!<br>
		You can market your tournaments!<br><br>

		If you are a golfer:<br><br>
		You can find tournaments that you like here!<br>
		You can register for tournaments!<br>
		You can pay for tournaments!<br>
		You can access real-time imformation about the tournaments!<br>
		You can check-in on the day of the tournaments! <br>
	</p>
</div>

app/views/home/contact.html.erb
<div class="container">
	<div class = "row">
		<h1>Contact us</h1>
		<h2>Ask us anything that you don't understand!</h2>
	</div>		

	<div class = "row">
		<div class = "col-md-6">
        <%= form_tag do %>
          <%= text_field_tag(:user,nil, placeholder: 'Your Name', class: 'form-control') %> <br><br>
          <%= email_field(:user, :address, placeholder: 'Your Email', class: 'form-control') %><br><br>
          <%= text_area_tag(:message, nil,placeholder: 'Your Message', size: "24x6", class: 'form-control') %><br>
          <%= submit_tag("Submit!", class: 'form-control') %>
        <% end %>
        </div>
    </div>
</div>

app/views/home/faq.html.erb
<div class="container">
  <h1>FAQs</h1> 
  <h3>General Questions</h3>
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                    Is account registration required?
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                    You do not need an account to view active tournaments. An account is required to create, sponsor, or join a tournament.
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">What forms of payment does Golfly accept?</a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                    Golfly currently only accepts Paypal payments.
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">What is the refund policy?</a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
                <div class="panel-body">
                    Golfly will only refund the price of the ticket if the cancellation is 48hours before the start of the event.
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<div id="headerwrap">
    <div class="container">
      <h1>Golfly</h1>
      <h3>The easy way to host golf tournaments.</h3>
      <%= link_to 'Create Tournament', new_tournament_path, {:class=>"btn btn-success"} %>
      <%= link_to 'Tournament Listings', tournaments_path, {:class=>"btn btn-primary"} %>
    </div>
</div><!-- /headerwrap -->

<div class="container">
  <div class="row centered">
    <h1>Features</h1><br><hr>
      <div class="col-md-4" id="featured-tournaments">
        <%= image_tag("browser.png", size: "200x200", class: "img-rounded")%>
        <!-- <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>-->
        <h2>Organize</h2>
        <p>Manage and create your own tournament page</p>
      </div>
      <div class="col-md-4" id="featured-tournaments">
        <%= image_tag("golf.png", size: "200x200", class: "img-rounded")%>
       <!-- <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>-->
        <h2>Golf</h2>
        <p> Browse and Sign-up for Tournaments through our immense list!</p>
      </div>
      <div class="col-md-4" id="featured-tournaments">
        <%= image_tag("money-bag.png", size: "200x200", class: "img-rounded")%>
       <!-- <div>Icons made by <a href="http://www.flaticon.com/authors/madebyoliver" title="Madebyoliver">Madebyoliver</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>-->
        <h2>Sponsor</h2>
        <p>Gain Sponsorship easily with our ticketing and payment system</p>
      </div>
  </div>
</div>

app/views/home/privacy.html.erb
<div class="container">
  <h1>Privacy</h1> 
  <p> Not sure what to put here.
</div>

app/views/home/sitemap.html.erb
<div class="container">
    <h1>Site Map</h1> 
    
    <ul class="indent_ul">
        <li><%= link_to t('application.home'), root_path %></li>
        <ul class="indent_ul_ul">
          <li><%= link_to t('application.about'), about_path %></li>
          <li><%= link_to t('application.contact'), contact_path %></li>
          <li><%= link_to t('application.faqs'), faq_path %></li>
          <li><%= link_to t('application.privacy_policy'), privacy_path %></li>
        </ul>
        <li><%= link_to t('application.tournaments'), tournaments_path %></li>
        <ul class="indent_ul_ul">
          <li><%= link_to t('tournaments.new.title'), new_tournament_path %></li>
        </ul>
    </ul>
</div>

app/views/home/tos.html.erb
<div class="container">
  <h1>Terms of Service</h1> 
  <p> Not sure what to put here.
</div>